AllCops:
  TargetRubyVersion: 3.1.2

  Exclude:
    - .gitignore
    - .rubocop.yml

    - Gemfile.lock
    - CHANGELOG.md
    - LICENSE.txt
    - README.md
    - Rakefile

    - node_modules/**/*
    - script/**/*
    - vendor/**/*

Style/StringLiterals:
  EnforcedStyle: double_quotes
